export enum Codes {
  INITIALIZATION = 1,
  PASSWORD = 2,
  ID_CREATION = 3,
  ID_LIST_REQUEST = 4,
  ID_LIST = 5,
  ID_AND_WORD = 6,
  GAME_STARTED_LEADING = 7,
  GAME_STARTED_GUESSING = 8,
  GUESS = 9,
  GAME_ENDED = 10,
  GUESS_WRONG = 11,
  ERROR = 12,
  HINT_REQUEST = 13,
  HINT = 14,
  HINT_SENT = 15,
  HINT_RECEIVED = 16,
  GIVE_UP = 17
}